import React from "react";
import Link from "next/link";
import CommonButton from "../Components/Shared/Button/Button";
import Head from 'next/head'

const About = () => {
  
  return (
    <div>
      <Head>
        <title>about</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>about</h1>
      </div>
    </div>
    
  );
};

export default About;
