import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";
import Header from "../Components/Header/Header";
import StrongPerformer from "../Components/StrongPerformer/StrongPerformer";
import DeveloperSection from "../Components/DeveloperSection/DeveloperSection";
import RecommendedSection from "../Components/RecommendedSection/RecommendedSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Xponents</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header></Header>
        <StrongPerformer />
        <DeveloperSection />
        <RecommendedSection/>
      </main>
    </div>
  );
}
